### ISSUE TITLE
AirVPN Stalled Connections

### ISSUE THREAD

**Issue by Nuccah** [ianharrier/synology-scripts#1]
Hey,

Great script - works for the most part however on network disconnect where I am (hello from the Congo!) my VPN (AirVPN) maintains an Up status. So the script doesn't detect that there is an issue although network is down.

I hacked it real quick to make it work for me by replacing your Uptime check by sampling RX between a 15s sleep which so far is working quite well. Might be better to just do a ping though instead of checking uptime or RX ? 

I'm not much of a bash scripter or I'd contribute more but I can get by ;)

**Comment by GamerGun** [comment]
Hi,
Have a look at my post here :)
https://community.synology.com/enu/forum/17/post/53791?page=9

**Comment by Nuccah** [comment]
That should do the trick :) thanks !
