### ISSUE TITLE
Gateway wouldn't ping, but VPN host does

### ISSUE THREAD

**Issue by michaelherger** [ianharrier/synology-scripts#13]
My DS is connected to another DS using OpenVPN. In this configuration the host VPN would be 10.8.0.1, the gateway 10.8.0.5, and the client DS 10.8.0.6. In that configuration the gateway would not ping, but the host (10.8.0.1) would. So... changing the second grep statement from `([0-9]+\.){3}[0-9]+ dev` to `([0-9]+\.){3}[0-9]+ via` would make the script work in `gateway_ping` mode.

https://github.com/ianharrier/synology-scripts/blob/171aa866e5a5d20b991351b7519eba63d0f4fe7e/reconnect-vpn.sh#L77

Without that modification the check would always fail, thus restart the VPN whenever the script is run...

**Comment by ianharrier** [comment]
Would you please run the following as root and send me the output? I'd like to compare with the output from my system.
```shell
ip route | grep $(ip addr | grep $(/usr/syno/bin/synovpnc get_conn | grep "Client IP" | awk '{ print $4 }') | awk '{ print $7 }')
```

**Comment by michaelherger** [comment]
```
ash-4.3# ip route | grep $(ip addr | grep $(/usr/syno/bin/synovpnc get_conn | grep "Client IP" | awk '{ print $4 }') | awk '{ print $7 }')
10.8.0.5 dev tun0  proto kernel  scope link  src 10.8.0.6 
10.8.0.1 via 10.8.0.5 dev tun0 
10.8.0.0/24 via 10.8.0.5 dev tun0 
```

**Comment by Forest14** [comment]
Experiencing same problem as @michaelherger using a public VPN service. These inherently become busy or unstable and require to reconnect. Typically on a Saturday night but also at other random times during business days.
I guess the script should be modified to ping a very reliable IP address (always responding). It seems that 4.2.2.2 is a good candidate. (Source: https://community.spiceworks.com/topic/107763-best-ip-address-to-ping-to-monitor-if-internet-is-up )
@ianharrier Possible and easy to do? I wish I had the right skillset to actually propose the code which would solve this!
Thanks

**Comment by melbnz** [comment]
After reading the other open issues i have resolved this by following: "issue after updating to Synology DSM 7.1 https://github.com/ianharrier/synology-scripts/issues/16"
Edit the script TUNNEL_INTERFACE=$(ip addr | grep $CLIENT_IP | awk '{ print $7 }') to be $5 not $7
Thanks clever people :-)

**Comment by Noone2018b** [comment]
Same issue for me - it seems like my VPN gateway (via SurfShark) won't respond to pings, but I do want a ping test since DSM often reports the connection is OK when it has, in fact, dropped somehow.

Quick and dirty fix is to hack in the desired test IP directly, either add it at line 77 or to the top of the script and comment out line 77 (marginally cleaner!).

https://github.com/ianharrier/synology-scripts/blob/171aa866e5a5d20b991351b7519eba63d0f4fe7e/reconnect-vpn.sh#L77

E.g. simply set `GATEWAY_IP=8.8.8.8` for Google ping test.

**Comment by ianharrier** [comment]
Please let me know if you think the new `custom_ping` option in the yet-to-be-released version 1.3.0 (https://github.com/ianharrier/synology-scripts/blob/feature/domainCheckMethod/reconnect-vpn.sh) would solve this issue. Thanks!

**Comment by ianharrier** [comment]
The new `custom_ping` option has been officially released. Please check out the latest version, and feel free to re-open this issue if that doesn't work as a workaround. Thanks!

**Comment by Noone2018b** [comment]
Looks great @ianharrier - and much neater than my quick hack :)  

I didn't test as yet, but will let you know as and when I do.
