### ISSUE TITLE
Is there a way to use this script with multiple VPN Connections ?

### ISSUE THREAD

**Issue by BobWs** [ianharrier/synology-scripts#18]
Hi,
I have multiple OpenVPN connection setup in DSM for easy access to different OpenVPN Servers.
I have read that your script only works with one vpn connection added in DSM, so my question is if it is possible to alter the script to use when there are multiple VPN connections.

**Comment by ianharrier** [comment]
Yes – version 1.4.0 was just released. With the new `VPN_PROFILE_NAME` option, you can run multiple instances of the script, each targeting a specific VPN profile.
