### ISSUE TITLE
Is there a way to add a Telegram notification to the mix?

### ISSUE THREAD

**Issue by BobWs** [ianharrier/synology-scripts#19]
Hi,
Is there a way to set telegram notification to the script to send the notifications through Telegram?
How are you getting your notifications when VPN is down and the script has establish re connection?

**Comment by ianharrier** [comment]
Currently, there is no plan to implement Telegram notifications. However, email notifications are supported, per the instructions on the [blog post](https://blog.harrier.us/reconnecting-a-failed-vpn-connection-on-synology-dsm-6) I wrote about this script.
