### ISSUE TITLE
Download Station in pause

### ISSUE THREAD

**Issue by Kris-I** [ianharrier/synology-scripts#24]
Hello,

It's not really an issue but one more feature, if possible, to add. I don't know anything about sonology script.

Is it possible to change torrent status to "pause" when it' not possuble to connect to the VPN and the opposite switch torrent "Start" when the VPN is connected.

Your script works fine ! 

Thanks

**Comment by ianharrier** [comment]
Unfortunately, your use case falls outside the scope of this script. However, #23 is similar to your question, and as I mentioned there, version 1.5.0 of this script adds the ability to run external scripts. You could potentially make use of the external script feature to do what you're describing.
