### ISSUE TITLE
Keep trying to reconnect after a long disconnection

### ISSUE THREAD

**Issue by Mic13710** [ianharrier/synology-scripts#25]
Hello,
I have installed this script on a DS214+ to keep a permanent VPN connection with a DS713+ for cross backup.
The VPN server is on the DS713+ and the connection is in L2TP/IPSec mode.
The script uses dsm_status only.
It works well for short duration reconnections.
However, I face an issue with long duration disconnections of the VPN server.
When 713+ is shutdown for a while (power failure for instance), the script is not able to reconnect once the server is back to work.
The 214+ VPN link stays in connection process and each attempt by the script to reconnect fails with this message : Scheduled task [Reconnect VPN] skipped because the task was already running
The only solution I have found is disconnecting the VPN to kill the connection process. It is only after the disconnection that the script is able to do its work as scheduled.
It seems that "/usr/syno/bin/synovpnc kill_client" does not kill the connection. I have tried to extend the sleep to 30 with no result.
I wonder if it would not be preferable to first attempt to reconnect with "/usr/syno/bin/synovpnc reconnect" before trying to kill ?
Thanks to have a look to this issue.
Michel

**Comment by ianharrier** [comment]
As described in the README, the reconnect logic in the script was taken from a post on the Synology Forum – basically [this entire chunk](https://github.com/ianharrier/synology-scripts/blob/master/reconnect-vpn.sh#L154-L162). I'm hesitant to change that portion of the script without some data to suggest that making a change would actually be an improvement. If you'd like to do some testing and provide your results, I'd be willing to consider incorporating this change. I'm going to close this issue for now, but feel free to re-open if you have some data to share on this change.
