### ISSUE TITLE
Ping does not work reliable 

### ISSUE THREAD

**Issue by Steven-2023** [ianharrier/synology-scripts#26]

**Comment by ianharrier** [comment]
Hi @Steven-2023, without some additional information about your setup and which of the two ping options you're using (i.e. `gateway_ping` or `custom_ping`), it's going to be difficult to troubleshoot the issue you're experiencing. That being said, you can always use the default `dsm_status` check method if you're experiencing issues with the other method(s). I'm going to close this, but feel free to re-open if you want to provide some additional info.
