### ISSUE TITLE
Add specific package stop

### ISSUE THREAD

**Issue by francoiswinkel** [ianharrier/synology-scripts#6]
Hello,
Do you think you could add to your script an extra command to, in case no VPN, stop a specific package (for instance Download Station) and then try to reconnect and if successful restart the package?

Thanks
Best regards
François

**Comment by ianharrier** [comment]
In an effort to avoid scope creep, I'm wondering if you might be able to call `reconnect-vpn.sh` from another script. A non-zero exit code from `reconnect-vpn.sh` indicates that either an error occurred or the VPN connection was offline when the script started (whether the reconnect was successful or not). You could use the exit code from `reconnect-vpn.sh` to trigger the restart of a Synology package, as follows (where you would replace `<packageName>` with the name of a package returned by `synoservice --list`):

```bash
#!/usr/bin/env bash

/path/to/reconnect-vpn.sh

if [ "$?" != "0" ]; then
    /usr/syno/sbin/synoservicectl --restart <packageName>
fi
```

I would also be open to having more useful exit codes in `reconnect-vpn.sh`. For example:

- `0`: reconnect is not needed
- `1`: reconnect was successful
- `2`: reconnect failed
- `3`: configuration error

If that change was made to `reconnect-vpn.sh`, you could modify the script above to the following, which would functionally prevent the package from being restarted if there were subsequent failed reconnects:

```bash
#!/usr/bin/env bash

/path/to/reconnect-vpn.sh

if [ "$?" = "1" ]; then
    /usr/syno/sbin/synoservicectl --restart <packageName>
fi
```

Please let me know your thoughts on this solution. I'd be happy to modify the exit codes if you think that would help in your use case.

**Comment by DummerJunge** [comment]
I really second the idea having some differentiated exit codes.

**Comment by ianharrier** [comment]
@DummerJunge What are your thoughts on the ones I listed above? Would you suggest any changes to those?

**Comment by DummerJunge** [comment]
Hm, AFAIK there is no standard for exit codes, besides 0 for success. Also you have one exit code for all different results. That's great, thanks, no changes.

**Comment by ianharrier** [comment]
I just pushed version 1.2.0, which includes the exit codes listed above.

**Comment by DummerJunge** [comment]
GREAT, thank you.
