### ISSUE TITLE
won't work for me

### ISSUE THREAD

**Issue by Meteo07** [ianharrier/synology-scripts#7]
Hi,sorry for my bad english, i'm french, i've tested the script, and it doesen't work for me, if openvpn was connected (after a connection loss by modem for example) the script don't see this and don't reconnect 

in dsm at this time vpn is connected status but no trafic is possible... 

can you help me please? 

Regards

oh sorry i don"t see the option for ping... yes it's good !!! 

thanks

**Comment by ianharrier** [comment]
Hi @Meteo07, I saw that you modified version 1.2.0 of the script [here](https://github.com/ianharrier/synology-scripts/commit/6b8b9f7ad4bf1a6103dede629e3be47b6c2521c6#commitcomment-48043431). Are you having problems with your modified version or with the original script?

**Comment by Meteo07** [comment]
no it's okay i haven't see the three options: ping, dsm status, or connected/disconnected...

**Comment by ianharrier** [comment]
Sounds good! I'll go ahead and close this issue then.
