### ISSUE TITLE
Forum link broken

### ISSUE THREAD

**Issue by ltickett** [ianharrier/synology-scripts#8]
This link is no longer valid (from README.md): https://forum.synology.com/enu/viewtopic.php?f=241&t=65444

Is this the updated link on the new forum perhaps? https://community.synology.com/enu/forum/17/post/53791

Or maybe just link to the forum https://community.synology.com/enu/ or remove the link entirely?

**Comment by ianharrier** [comment]
Thanks! I just updated the script with the new URL.
